### ISSUE TITLE
Ability to export

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/AchillesWeb#41]
It would be great if I could export all data into CSV file. (not just view it on the web)
Just plain export all data button. (no complex filtering)

If this is sensitive issue (e.g., for lab) allow at least to export  Achilles Heel Report data only.

When using IMEDS install of Achilles, I have no access to the JSON files or the DB schema with Achilles results so viewing on the web (and "webscraping it off the AchillesWeb is the only way to see them all.

(also drop down option to see "all results" (in D3 data table viewer) would be great.)

**Comment by chrisknoll** [comment]
An export to csv on the achilles heel report sounds reasonable. Doing it for all data would be a pretty big CSV file (on the order of 100+ MB).  I'll look into this.
